import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from './App';

const user = { id: 'user-1', username: 'ana', role: 'PATIENT', status: 'ACTIVE' };
const admin = { id: 'admin-1', username: 'admin', role: 'ADMINISTRATOR', status: 'ACTIVE' };

beforeEach(() => { vi.restoreAllMocks(); vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('offline'))); });

describe('authentication flow', () => {
  it('renders the login form', async () => { render(<App />); expect(await screen.findByRole('heading', { name: 'Bienvenido de nuevo' })).toBeInTheDocument(); expect(screen.getByRole('textbox', { name: /Usuario/ })).toBeInTheDocument(); expect(screen.getByLabelText('Contraseña', { exact: false })).toBeInTheDocument(); });

  it('renders required patient registration fields', async () => { const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.click(screen.getByRole('button', { name: /regístrate/i })); expect(screen.getByLabelText('Nombre completo')).toBeRequired(); expect(screen.getByLabelText('Fecha de nacimiento')).toBeRequired(); expect(screen.getByLabelText('Sexo')).toBeRequired(); expect(screen.getByRole('textbox', { name: /CI boliviano/ })).toBeRequired(); expect(screen.getByLabelText('Confirmar contraseña')).toBeRequired(); });

  it('prevents invalid registration submission', async () => { const fetchMock = vi.mocked(fetch); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.click(screen.getByRole('button', { name: /regístrate/i })); await ui.click(screen.getByRole('button', { name: 'Crear cuenta' })); expect(await screen.findByRole('alert')).toHaveTextContent(/Completa los campos requeridos|contraseña debe tener/); expect(fetchMock).toHaveBeenCalledTimes(1); });

  it('logs in with credentials and loads the patient profile', async () => { const fetchMock = vi.mocked(fetch).mockImplementation(async (input) => { const url = String(input); if (url.includes('/auth/session')) return new Response('{}', { status: 401 }); if (url.includes('/auth/login')) return new Response(JSON.stringify({ user }), { status: 201 }); if (url.includes('/auth/patient-profile')) return new Response(JSON.stringify({ medicalHistory: 'Hipertensión controlada', allergies: 'Penicilina', currentMedications: 'Losartán', chronicConditions: 'Asma' }), { status: 200 }); return new Response('{}', { status: 404 }); }); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.type(screen.getByRole('textbox', { name: /Usuario/ }), 'ana'); await ui.type(screen.getByLabelText('Contraseña', { exact: false }), 'Secret123'); await ui.click(screen.getByRole('button', { name: 'Ingresar' })); await screen.findByRole('heading', { name: 'Hola, ana' }); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/auth/login'), expect.objectContaining({ credentials: 'include', method: 'POST' })); expect(await screen.findByRole('heading', { name: 'Mi perfil clínico' })).toBeInTheDocument(); expect(screen.getByLabelText('Antecedentes médicos')).toHaveValue('Hipertensión controlada'); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/auth/patient-profile'), expect.objectContaining({ credentials: 'include' })); });

  it('shows an API error', async () => { const fetchMock = vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response('{}', { status: 401 }) : new Response(JSON.stringify({ message: 'Credenciales inválidas' }), { status: 401 })); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.type(screen.getByRole('textbox', { name: /Usuario/ }), 'ana'); await ui.type(screen.getByLabelText('Contraseña', { exact: false }), 'wrong'); await ui.click(screen.getByRole('button', { name: 'Ingresar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Credenciales inválidas'); });

  it('logs out and returns to login', async () => { vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response(JSON.stringify(user)) : new Response('{}', { status: 200 })); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Hola, ana' }); await ui.click(screen.getByRole('button', { name: 'Cerrar sesión' })); await waitFor(() => expect(screen.getByRole('heading', { name: 'Bienvenido de nuevo' })).toBeInTheDocument()); });
  it('clears frontend auth state when logout API fails', async () => { vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response(JSON.stringify(user)) : new Response(JSON.stringify({ message: 'offline' }), { status: 503 })); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Hola, ana' }); await ui.click(screen.getByRole('button', { name: 'Cerrar sesión' })); await waitFor(() => expect(screen.getByRole('heading', { name: 'Bienvenido de nuevo' })).toBeInTheDocument()); });
  it('shows provisioning only to administrators', async () => { vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response(JSON.stringify(admin)) : new Response('{}', { status: 200 })); render(<App />); expect(await screen.findByRole('heading', { name: 'Crear cuenta de personal' })).toBeInTheDocument(); expect(screen.getByLabelText('Rol asignado')).toBeInTheDocument(); });
  it('provisions a selected account and reports success', async () => { const fetchMock = vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response(JSON.stringify(admin)) : new Response(JSON.stringify({ id: 'new', username: 'doctor', role: 'PHYSICIAN' }), { status: 201 })); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Crear cuenta de personal' }); await ui.type(screen.getByLabelText('Nombre completo'), 'Dr. García'); await ui.type(screen.getByLabelText('Fecha de nacimiento'), '1980-01-01'); await ui.type(screen.getByLabelText('CI boliviano'), '12345'); await ui.type(screen.getByLabelText('Usuario'), 'doctor'); await ui.type(screen.getByLabelText('Contraseña'), 'Secret123'); await ui.selectOptions(screen.getByLabelText('Sexo'), 'MALE'); await ui.click(screen.getByRole('button', { name: 'Crear cuenta' })); expect(await screen.findByRole('status')).toHaveTextContent('Cuenta creada correctamente.'); expect(fetchMock).toHaveBeenLastCalledWith(expect.stringContaining('/auth/users'), expect.objectContaining({ method: 'POST' })); });
  it('reports provisioning API errors', async () => { vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response(JSON.stringify(admin)) : new Response(JSON.stringify({ message: 'Usuario ya existe' }), { status: 409 })); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Crear cuenta de personal' }); await ui.type(screen.getByLabelText('Nombre completo'), 'Dr. García'); await ui.type(screen.getByLabelText('Fecha de nacimiento'), '1980-01-01'); await ui.type(screen.getByLabelText('CI boliviano'), '12345'); await ui.type(screen.getByLabelText('Usuario'), 'doctor'); await ui.type(screen.getByLabelText('Contraseña'), 'Secret123'); await ui.selectOptions(screen.getByLabelText('Sexo'), 'MALE'); await ui.click(screen.getByRole('button', { name: 'Crear cuenta' })); expect((await screen.findAllByRole('alert'))[0]).toHaveTextContent('Usuario ya existe'); });
  it('opens recovery, validates required fields, and returns to login', async () => { const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.click(screen.getByRole('button', { name: /olvidaste/i })); expect(screen.getByRole('heading', { name: 'Recupera tu contraseña' })).toBeInTheDocument(); await ui.click(screen.getByRole('button', { name: 'Restablecer contraseña' })); expect(await screen.findByRole('alert')).toHaveTextContent(/Completa los campos requeridos|contraseña debe tener/); await ui.click(screen.getByRole('button', { name: /volver al inicio/i })); expect(await screen.findByRole('heading', { name: 'Bienvenido de nuevo' })).toBeInTheDocument(); });
  it('shows recovery success and API errors', async () => { const fetchMock = vi.mocked(fetch).mockImplementation(async (input) => String(input).includes('/auth/session') ? new Response('{}', { status: 401 }) : new Response(JSON.stringify({ success: true }), { status: 200 })); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.click(screen.getByRole('button', { name: /olvidaste/i })); await ui.type(screen.getByLabelText('Usuario'), 'patient'); await ui.type(screen.getByLabelText('CI boliviano'), '12345'); await ui.type(document.querySelector('#newPassword')!, 'NewSecret123'); await ui.click(screen.getByRole('button', { name: 'Restablecer contraseña' })); expect(await screen.findByRole('status')).toHaveTextContent('Contraseña actualizada'); expect(fetchMock).toHaveBeenLastCalledWith(expect.stringContaining('/auth/recover-password'), expect.objectContaining({ method: 'POST' })); });
  it('shows a user-visible recovery error when the API request rejects', async () => { vi.mocked(fetch).mockImplementation(async (input) => { if (String(input).includes('/auth/session')) return new Response('{}', { status: 401 }); throw new Error('offline'); }); const ui = userEvent.setup(); render(<App />); await screen.findByRole('heading', { name: 'Bienvenido de nuevo' }); await ui.click(screen.getByRole('button', { name: /olvidaste/i })); await ui.type(screen.getByLabelText('Usuario'), 'patient'); await ui.type(screen.getByLabelText('CI boliviano'), '12345'); await ui.type(document.querySelector('#newPassword')!, 'NewSecret123'); await ui.click(screen.getByRole('button', { name: 'Restablecer contraseña' })); expect(await screen.findByRole('alert')).toHaveTextContent('No se pudo restablecer la contraseña con los datos proporcionados.'); });
});
