import * as React from 'react';
import { request, type User } from '../../lib/api';
import { Button } from '../../components/ui/Button';
import { FormField } from '../../components/ui/FormField';
import { Select } from '../../components/ui/Select';
import { LOGOUT_PENDING_KEY } from '../../app/App';

type Mode = 'login' | 'register';
export function AuthForm({ mode, onSuccess, error, setError }: { mode: Mode; onSuccess: (user: User) => void; error: string; setError: (value: string) => void }) {
  const [form, setForm] = React.useState<Record<string, string>>({}); const [busy, setBusy] = React.useState(false);
  const update = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); const required = mode === 'register' ? ['fullName', 'dateOfBirth', 'sex', 'nationalId', 'username', 'password', 'passwordConfirmation'] : ['username', 'password']; if (required.some((field) => !form[field]?.trim())) { setError('Completa los campos requeridos.'); return; } if (mode === 'register' && form.password !== form.passwordConfirmation) { setError('Las contraseñas no coinciden.'); return; } setBusy(true); try { const data = await request<{ user: User }>(mode === 'login' ? '/auth/login' : '/auth/register', { method: 'POST', body: JSON.stringify(form) }); if (mode === 'login') localStorage.removeItem(LOGOUT_PENDING_KEY); onSuccess(data.user); } catch (err) { setError(err instanceof Error ? err.message : 'Error inesperado.'); } finally { setBusy(false); } };
  return <form className="grid gap-4" onSubmit={submit} noValidate>{mode === 'register' && <><Field label="Nombre completo" name="fullName" value={form.fullName} onChange={update('fullName')} required /><Field label="Fecha de nacimiento" name="dateOfBirth" type="date" value={form.dateOfBirth} onChange={update('dateOfBirth')} required /><FormField label="Sexo" name="sex" value={form.sex ?? ''} onChange={update('sex')} required><Select id="sex" name="sex" value={form.sex ?? ''} onChange={update('sex')} required><option value="">Selecciona</option><option value="FEMALE">Femenino</option><option value="MALE">Masculino</option></Select></FormField><Field label="CI boliviano" name="nationalId" inputMode="numeric" value={form.nationalId} onChange={update('nationalId')} required /><Field label="Dirección (opcional)" name="address" value={form.address} onChange={update('address')} /></>}<Field label="Usuario" name="username" value={form.username} onChange={update('username')} required /><Field label="Contraseña" name="password" type="password" value={form.password} onChange={update('password')} required />{mode === 'register' && <Field label="Confirmar contraseña" name="passwordConfirmation" type="password" value={form.passwordConfirmation} onChange={update('passwordConfirmation')} required />}{error && <p className="rounded-[9px] bg-[#fff1f0] p-3 text-[13px] text-[#b53b36]" role="alert">{error}</p>}<Button type="submit" disabled={busy}>{busy ? 'Procesando…' : mode === 'login' ? 'Ingresar' : 'Crear cuenta'}</Button></form>;
}
function Field(props: { label: string; name: string; value?: string; onChange: (event: React.ChangeEvent<HTMLInputElement>) => void; type?: string; required?: boolean; inputMode?: 'numeric' }) { return <FormField {...props} />; }
