import * as React from 'react';
import { provisionUser, type ManagedRole, type User } from '../../lib/api';
import { Button } from '../../components/ui/Button';
import { FormField } from '../../components/ui/FormField';
import { Select } from '../../components/ui/Select';

export function AdminProvisioning() {
  const [form, setForm] = React.useState<Record<string, string>>({ role: 'PHYSICIAN' }); const [busy, setBusy] = React.useState(false); const [message, setMessage] = React.useState(''); const [error, setError] = React.useState('');
  const update = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); setError(''); if (Object.entries(form).some(([key, value]) => key !== 'address' && !value?.trim())) { setError('Completa los campos requeridos.'); return; } setBusy(true); try { await provisionUser(form as unknown as Parameters<typeof provisionUser>[0]); setMessage('Cuenta creada correctamente.'); setForm({ role: form.role }); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo crear la cuenta.'); } finally { setBusy(false); } };
  return <section aria-labelledby="admin-title" className="mx-auto mt-[8vh] w-full max-w-[640px] rounded-[clamp(16px,3vw,22px)] border border-[#dce7ee] bg-white p-[clamp(22px,5vw,34px)] shadow-[0_18px_50px_#20425d12]"><p className="mb-2 text-[11px] font-extrabold uppercase tracking-[.12em] text-[#147d7e]">Administración</p><h1 id="admin-title" className="mb-2 text-[clamp(25px,7vw,30px)] font-bold leading-tight tracking-[-.04em]">Crear cuenta de personal</h1><p className="mb-6 leading-relaxed text-[#678096]">Registra médicos, ayudantes y administradores del sistema.</p><form className="grid gap-4" onSubmit={submit} noValidate><div className="grid grid-cols-1 gap-3 min-[561px]:grid-cols-2"><FormField label="Nombre completo" name="fullName" value={form.fullName ?? ''} onChange={update('fullName')} required /><FormField label="Fecha de nacimiento" name="dateOfBirth" type="date" value={form.dateOfBirth ?? ''} onChange={update('dateOfBirth')} required /></div><div className="grid grid-cols-1 gap-3 min-[561px]:grid-cols-2"><FormField label="CI boliviano" name="nationalId" value={form.nationalId ?? ''} onChange={update('nationalId')} required /><FormField label="Usuario" name="username" value={form.username ?? ''} onChange={update('username')} required /></div><div className="grid grid-cols-1 gap-3 min-[561px]:grid-cols-2"><FormField label="Contraseña" name="password" type="password" value={form.password ?? ''} onChange={update('password')} required /><FormField label="Dirección (opcional)" name="address" value={form.address ?? ''} onChange={update('address')} /></div><FormField label="Sexo" name="sex" value={form.sex ?? ''} onChange={update('sex')} required><Select id="sex" name="sex" value={form.sex ?? ''} onChange={update('sex')} required><option value="">Selecciona</option><option value="FEMALE">Femenino</option><option value="MALE">Masculino</option></Select></FormField><FormField label="Rol asignado" name="role" value={form.role ?? 'PHYSICIAN'} onChange={update('role')} required><Select id="role" name="role" value={form.role ?? 'PHYSICIAN'} onChange={update('role')} required><option value="PHYSICIAN">Médico</option><option value="ASSISTANT">Ayudante</option><option value="ADMINISTRATOR">Administrador</option></Select></FormField>{error && <p className="rounded-[9px] bg-[#fff1f0] p-3 text-[13px] text-[#b53b36]" role="alert">{error}</p>}{message && <p className="rounded-[9px] bg-[#e9f6f4] p-3 text-[13px] text-[#176b6b]" role="status">{message}</p>}<Button type="submit" disabled={busy}>{busy ? 'Creando…' : 'Crear cuenta'}</Button></form></section>;
}
